version: "3.8"

services:
  mongodb:
    image: mongo_mienvio
    container_name: monguito
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/mienvio2-admin/mongodb/database:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped