version: "3.8"

services:
  mienvio_mongodb-1:
    image: mongo:latest
    command: ["mongod", "--replSet", "rs"]
    ports:
      - '27017:27017'
    networks:
      - mienvio_net
    volumes:
      - mienvio_data:/data/db
      - mienvio_config:/data/configdb
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
      placement:
        constraints:
          - node.role == manager

  mienvio_mongodb-2:
    image: mongo:latest
    command: ["mongod", "--replSet", "rs"]
    ports:
      - '27018:27017'
    networks:
      - mienvio_net
    volumes:
      - mienvio_data:/data/db
      - mienvio_config:/data/configdb
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
      placement:
        constraints:
          - node.role == worker

networks:
  mienvio_net:
    external: true

volumes:
  mienvio_data:
  mienvio_config: