name: Release application

on:
  push:
    branches:
      - frontend

permissions: write-all

jobs:

  avoid_redundancy:

    name: Check skip
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build_artifact:

    name: Build android artifact
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'

      - name: Install dependencies
        run: flutter pub get

      - name: Build application
        run: flutter build apk

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MiEnvio
          path: ${{ secrets.ARTIFACT_PATH }}
  
  release:
  
    needs: [build_artifact] 
    permissions: write-all

    name: Create Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: MiEnvio
          path: ${{ secrets.ARTIFACT_PATH }}
      
      - name: Move apk to home
        run: mv ${{ secrets.ARTIFACT_PATH }} ./MiEnvio

      - name: Delete unused folders
        run: rm -rf ./build/

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}

      - name: Update file to release
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ secrets.ASSET_PATH}}
          asset_name: MiEnvio.apk
          asset_content_type: application/zip
