name: Release application

on:
  push:
    branches:
      - frontend

permissions: write-all

jobs:

  avoid_redundancy:

    name: Check skip
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build_android_artifact:

    name: Build android artifact
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
          
      - name: Set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'

      - name: Install dependencies
        run: flutter pub get

      - name: Build application
        run: flutter build apk
        
      - name: Where am I
        run: pwd
        
      - name: What is here
        run: ls -l
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MiEnvio_android
          path: /home/runner/work/MiEnvio/MiEnvio/frontend/build/app/outputs/flutter-apk/app-release.apk
  
  build_ios_artifact:
  
    name: Build ios artifact
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
        
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'

      - name: Install dependencies
        run: flutter pub get

      - name: Build application
        run: flutter build ios --release --no-codesign

      - name: Where am I
        run: pwd
  
      - name: What is here
        run: ls -l
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MiEnvio_ios
          path: /Users/runner/work/MiEnvio/MiEnvio/frontend/build/ios/iphoneos/Runner.app
  
  release:
  
    needs: [build_android_artifact, build_ios_artifact] 
    permissions: write-all

    name: Create Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    
      - name: Check out the repo
        uses: actions/checkout@v3
    
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}

      - name: Download android artifact
        uses: actions/download-artifact@v3
        with:
          name: MiEnvio_android 
      
      - name: Update android artifact to release
        id: upload_android_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app-release.apk 
          asset_name: MiEnvio.apk
          asset_content_type: application/zip

      - name: Make directory
        run: mkdir /home/runner/work/MiEnvio/MiEnvio/frontend/ipa

      - name: Download ios artifact
        uses: actions/download-artifact@v3
        with:
          name: MiEnvio_ios
          path: /home/runner/work/MiEnvio/MiEnvio/frontend/ipa

      - name: Zip artifact
        run: zip -r Mienvio.zip /home/runner/work/MiEnvio/MiEnvio/frontend/ipa/
      
      - name: Move zip to ipa
        run: mv Mienvio.zip Mienvio.ipa

      - name: Where is the ipa file
        run: readlink -f Mienvio.ipa

      - name: What is here
        run: ls -l

      - name: Where am I
        run: pwd
      
      - name: Update ios artifact to release
        id: upload_ios_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Mienvio.ipa
          asset_name: MiEnvio.ipa
          asset_content_type: application/zip
  
